<?php 
	$assets_loc="../";
	$index_loc="../";
	$signin_loc="customer_signin.php";
	$signout_loc="customer_signout.php";
	$cart_loc="";
	$signin_who="customer_email";
	$admin_loc="../admin/";
	$search_box_loc="../";
	$search_action_loc="../product/";
?>